name: 'actions-govulncheck'
description: 'Run govulncheck'
inputs:
  version:
    description: 'Govulncheck version'
    required: true
    default: 'latest'
  args:
    description: 'Govulncheck args'
    required: true
    default: './...'
runs:
  using: "composite"
  steps:
    - 
      name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@${{ inputs.version }}
    - 
      name: Output govulcheck version
      run: goculncheck -version
    - 
      name: Run govulncheck
      run: govulncheck ${{ input.args }}
      shell: bash
